### ISSUE TITLE
Handle byes and forfeits in JaVaFo interface

### ISSUE THREAD

**Issue by cyanfish** [krystjan/heltour#18]
This isn't necessary for the team tournament (since teams can't get byes etc., only individuals), but will be needed for lone wolf pairing.

**Comment by cyanfish** [comment]
I've fixed this in the JavafoInstance class (though no code needs it yet).

For byes, set "opponent=None" on the JavafoPairing.
For forfeits, set "forfeit=True" on the JavafoPairing. However, I'm pretty sure this is unnecessary and doesn't affect the pairings.

**Comment by lakinwecker** [comment]
I believe forfeits do affect the pairings. JavaFo will try not to pair people that have played previously, and this tells JavaFo that they did not play.  

In our case (lonewolf specifically) it's interesting, because the reason why they didn't play might be important. If they were unable to reach an agreement on a time to play, we shouldn't pair them again.  If they forfeited because something came up and it's a random occurrence, then pairing them again can make sense.

We had a situation last season where two players were paired, were unable to find a common time, each received half a point, and then were paired again because they had not played each other.

**Comment by cyanfish** [comment]
That's a good point. The code has the capability in any case.

Funnily enough, it probably would have handled that situation correctly, since the transfer format has no concept of a "forfeit draw".
